#!/usr/bin/env python

# Copyright (C) 2010 Brailcom, o.p.s.
#
# COPYRIGHT NOTICE
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys

import pytis.extensions

def usage(optexception=None):
    sys.stderr.write("usage: %s [ --config=CONFIG_FILE ]\n")
    if optexception:
        sys.stderr.write(optexception.msg)
        sys.stderr.write('\n')
    sys.exit(1)

def run():
    import config
    try:
        config.add_command_line_options(sys.argv)
    except getopt.GetoptError, e:
        usage(e)
    reporter = pytis.extensions.CheckReporter()
    pytis.extensions.MenuChecker().batch_check(reporter)

if __name__ == '__main__':
    run()
