#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Copyright (C) 2026 Tomáš Cerha <t.cerha@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Check the published Pytis API for unnoticed changes.

The API defined by 'pytis.api' has a fixed contract with Pytis applications.
Unlike the internal Pytis APIs, it can not be changed freely -- removing a
member, renaming an argument or making an optional argument mandatory breaks
the applications using it.

The complete published API surface is recorded in 'pytis/api/signature.txt'.
This script compares the current state of the API to that record, so that no
change of the contract can pass unnoticed.  When the change is intended, the
record must be updated (using the '--update' option below) within the same
commit.  Thus the evolution of the published API is visible in the project
history as the history of that single file.

This check is also performed by 'test_api_signature' in 'pytis/api/api.py',
so it runs as a part of the test suite.

Usage:
  tools/check-api.py [--update | --against REVISION]

Options:
  --update: Rewrite the record according to the current state of the API
    instead of comparing to it.  Always inspect the resulting diff!
  --against REVISION: Compare to the API as defined in given Git revision
    (commit, branch, tag) rather than to the record and report only the
    changes which actually break the applications.  Useful for release notes.

Requires the 'griffe' package (part of the 'lint' extra dependencies).

Exits with 1 when any change is found, otherwise with 0.

"""

from __future__ import print_function

import difflib
import io
import logging
import os
import sys

PACKAGE = 'pytis.api'
DIRECTORY = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RECORD_FILE = os.path.join(DIRECTORY, 'pytis', 'api', 'signature.txt')
HEADER = (
    "# Signature of the public API defined by the '{}' module.\n"
    "#\n"
    "# Generated by 'tools/check-api.py --update'.  Do not edit manually.  Any\n"
    "# change in this file is a change of the contract with Pytis applications.\n"
).format(PACKAGE)


def _parameters(func):
    """Return the parameters of given Griffe function as a string."""
    result = []
    for param in func.parameters:
        if param.name == 'self':
            continue
        if param.kind.name == 'keyword_only' and '*' not in ''.join(result):
            result.append('*')
        prefix = {'var_positional': '*', 'var_keyword': '**'}.get(param.kind.name, '')
        arg = prefix + param.name
        if param.default is not None and not prefix:
            arg += '=' + str(param.default)
        result.append(arg)
    return '({})'.format(', '.join(result))


def _members(obj, prefix=''):
    """Return the public members of given Griffe object as a list of strings.

    Members with a name starting by an underscore are omitted as private, but
    special methods (such as '__getattr__' or '__len__') are included as they
    also belong to the public API (they define how the API objects behave).

    Members with the 'api_' prefix are omitted as well.  They belong to classes
    implementing an API, where the prefix distinguishes them from the internal
    Pytis API of the same class.  The applications never see these names -- they
    access them without the prefix through 'APIProvider', so the contract is
    already recorded through the corresponding API definition class.

    """
    import griffe
    result = []
    for name in sorted(obj.members):
        if name.startswith('api_') or (name.startswith('_') and not name.endswith('__')):
            continue
        member = obj.members[name]
        if member.is_alias and not member.target_path.startswith('pytis.'):
            # Names imported from other packages, such as 'print_function'
            # imported from '__future__', are not a part of the Pytis API.
            continue
        try:
            target = member.final_target if member.is_alias else member
        except griffe.AliasResolutionError:
            result.append(prefix + name)
            continue
        if target.is_module:
            continue
        elif target.is_function:
            result.append(prefix + name + _parameters(target))
        elif target.is_class:
            result.append(prefix + name)
            result.extend(_members(target, prefix=prefix + name + '.'))
        else:
            result.append(prefix + name)
    return result


def api_signature():
    """Return the signature of the published API as a string."""
    import griffe
    logging.getLogger('griffe').setLevel(logging.WARNING)
    return HEADER + '\n'.join(_members(griffe.load(PACKAGE, search_paths=[DIRECTORY]))) + '\n'


def check_record():
    """Compare the current API signature to the record.  Return a diff as a string."""
    signature = api_signature()
    with io.open(RECORD_FILE, encoding='utf-8') as f:
        record = f.read()
    return ''.join(difflib.unified_diff(
        record.splitlines(True), signature.splitlines(True),
        fromfile=os.path.relpath(RECORD_FILE, DIRECTORY), tofile='current API',
    ))


def update_record():
    """Rewrite the record according to the current state of the API."""
    with io.open(RECORD_FILE, 'w', encoding='utf-8') as f:
        f.write(api_signature())


def breaking_changes(revision):
    """Return breaking changes against given Git revision as a list of strings."""
    import griffe
    logging.getLogger('griffe').setLevel(logging.WARNING)
    old = griffe.load_git(PACKAGE, ref=revision, search_paths=[DIRECTORY])
    new = griffe.load(PACKAGE, search_paths=[DIRECTORY])
    return [b.explain(style=griffe.ExplanationStyle.ONE_LINE)
            for b in griffe.find_breaking_changes(old, new)]


def main(argv):
    args = argv[1:]
    if args == ['--update']:
        update_record()
        print("Updated {}.".format(os.path.relpath(RECORD_FILE, DIRECTORY)), file=sys.stderr)
        return 0
    elif len(args) == 2 and args[0] == '--against':
        changes = breaking_changes(args[1])
        for change in changes:
            print(change)
        print("{} breaking change(s) against '{}'.".format(len(changes), args[1]), file=sys.stderr)
        return 1 if changes else 0
    elif not args:
        diff = check_record()
        if diff:
            sys.stdout.write(diff)
            print("\nThe published API differs from {}.\n"
                  "If the change is intended, run 'tools/check-api.py --update'."
                  .format(os.path.relpath(RECORD_FILE, DIRECTORY)), file=sys.stderr)
            return 1
        print("The published API matches {}."
              .format(os.path.relpath(RECORD_FILE, DIRECTORY)), file=sys.stderr)
        return 0
    else:
        print(__doc__.strip(), file=sys.stderr)
        return 2


if __name__ == '__main__':
    sys.exit(main(sys.argv))
