(defun pytis-has-key ()
  (interactive)
  (goto-char (point-min))
  (while (re-search-forward "\\(\\<not +\\)?\\([.a-zA-Z0-9_]+\\)\\.has_key(" nil t)
    (let ((not (or (match-string 1) ""))
          (dict (match-string 2))
          (end (1- (match-end 0)))
          point)
      (goto-char end)
      (delete-region (match-beginning 0) end)
      (setq point (point))
      (forward-sexp)
      (delete-char -1)
      (insert " " not "in " dict)
      (goto-char point)
      (delete-char 1))))